import { inject, Injectable } from '@angular/core';
import { Supabase } from './supabase';
import { Order, OrderItem, OrderStatusHistory } from '@core/models/order';
import { OrderStatus, PaymentStatus } from '@core/enums';
import { TenantService } from './tenant';
import { AuthService } from './auth';

export interface OrderStats {
    totalThisMonth: number;
    pendingFulfillment: number;
    revenueToday: number;
    revenuePrevDay: number;
}

export interface OrderFilters {
    status?: OrderStatus;
    payment_status?: PaymentStatus;
    search?: string;
    startDate?: string;
    endDate?: string;
    customer_id?: string;
}

@Injectable({
    providedIn: 'root',
})
export class OrdersService {
    private readonly supabase = inject(Supabase);
    private readonly tenantService = inject(TenantService);
    private readonly authService = inject(AuthService);

    async getOrders(
        page: number = 1,
        pageSize: number = 20,
        filters?: OrderFilters
    ): Promise<{ data: Order[]; count: number }> {
        const tenantId = this.tenantService.tenantId();
        if (!tenantId) return { data: [], count: 0 };

        let query = this.supabase.client
            .from('orders')
            .select('*', { count: 'exact' })
            .eq('tenant_id', tenantId);

        // Apply delivery person filter if the current user has the 'delivery' role
        const role = this.tenantService.memberRole();
        const userId = this.authService.user()?.id;
        if (role === 'delivery' && userId) {
            query = query.eq('delivery_person_id', userId);
        }

        if (filters?.status) {
            query = query.eq('status', filters.status);
        }

        if (filters?.payment_status) {
            query = query.eq('payment_status', filters.payment_status);
        }

        if (filters?.search) {
            query = query.or(
                `order_number.ilike.%${filters.search}%,customer_email.ilike.%${filters.search}%,customer_first_name.ilike.%${filters.search}%,customer_last_name.ilike.%${filters.search}%`
            );
        }

        if (filters?.startDate) {
            query = query.gte('created_at', filters.startDate);
        }

        if (filters?.customer_id) {
            query = query.eq('customer_id', filters.customer_id);
        }

        if (filters?.endDate) {
            query = query.lte('created_at', filters.endDate);
        }

        query = query
            .order('created_at', { ascending: false })
            .range((page - 1) * pageSize, page * pageSize - 1);

        const { data, error, count } = await query;

        if (error) throw error;
        return { data: data as Order[], count: count ?? 0 };
    }

    async createOrder(orderData: Partial<Order>, items: Partial<OrderItem>[]): Promise<Order> {
        const tenantId = this.tenantService.tenantId();
        if (!tenantId) throw new Error('Tenant not selected');

        // Note: order_number is typically generated by DB trigger or needs manual sequence
        const fallbackOrderNumber = `ORD-${Date.now().toString().slice(-6)}`;

        const payload = {
            ...orderData,
            tenant_id: tenantId,
            order_number: orderData.order_number || fallbackOrderNumber,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
        };

        const { data: order, error: orderError } = await this.supabase.client
            .from('orders')
            .insert(payload as any)
            .select()
            .single();

        if (orderError) throw orderError;

        const orderItemsToInsert = items.map((item: any) => ({
            ...item,
            order_id: order.id,
            tenant_id: tenantId,
            created_at: new Date().toISOString()
        }));

        const { error: itemsError } = await this.supabase.client
            .from('order_items')
            .insert(orderItemsToInsert as any);

        if (itemsError) throw itemsError;

        try {
            await this.supabase.client.from('order_status_history').insert({
                order_id: order.id,
                tenant_id: tenantId,
                new_status: order.status || OrderStatus.Pending,
                note: 'Order created successfully',
            } as any);
        } catch (e) {
            console.warn('Could not insert order status history (likely RLS), ignoring:', e);
        }

        return order as Order;
    }

    async getOrder(id: string): Promise<Order | null> {
        let query = this.supabase.client
            .from('orders')
            .select(`
                *,
                items:order_items(*),
                status_history:order_status_history(*),
                refunds:refunds(*)
            `)
            .eq('id', id);

        // Apply delivery person filter if the current user has the 'delivery' role
        const role = this.tenantService.memberRole();
        const userId = this.authService.user()?.id;
        if (role === 'delivery' && userId) {
            query = query.eq('delivery_person_id', userId);
        }

        const { data, error } = await query.single();

        if (error) throw error;

        // Sort status history ascending by date
        if (data?.status_history) {
            (data.status_history as OrderStatusHistory[]).sort(
                (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime()
            );
        }

        return data as Order;
    }

    async getOrderStats(): Promise<OrderStats> {
        const tenantId = this.tenantService.tenantId();
        if (!tenantId) return { totalThisMonth: 0, pendingFulfillment: 0, revenueToday: 0, revenuePrevDay: 0 };

        const now = new Date();
        const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1).toISOString();
        const startOfToday = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();
        const startOfYesterday = new Date(now.getFullYear(), now.getMonth(), now.getDate() - 1).toISOString();

        // Base queries
        let monthQuery = this.supabase.client.from('orders').select('id', { count: 'exact', head: true }).eq('tenant_id', tenantId).gte('created_at', startOfMonth);
        let pendingQuery = this.supabase.client.from('orders').select('id', { count: 'exact', head: true }).eq('tenant_id', tenantId).in('status', ['pending', 'processing', 'paid']);
        let todayQuery = this.supabase.client.from('orders').select('total_amount').eq('tenant_id', tenantId).gte('created_at', startOfToday).neq('status', 'cancelled').neq('status', 'refunded');
        let yesterdayQuery = this.supabase.client.from('orders').select('total_amount').eq('tenant_id', tenantId).gte('created_at', startOfYesterday).lt('created_at', startOfToday).neq('status', 'cancelled').neq('status', 'refunded');

        // Apply delivery role filter
        const role = this.tenantService.memberRole();
        const userId = this.authService.user()?.id;
        if (role === 'delivery' && userId) {
            monthQuery = monthQuery.eq('delivery_person_id', userId);
            pendingQuery = pendingQuery.eq('delivery_person_id', userId);
            todayQuery = todayQuery.eq('delivery_person_id', userId);
            yesterdayQuery = yesterdayQuery.eq('delivery_person_id', userId);
        }

        const [monthRes, pendingRes, todayRes, yesterdayRes] = await Promise.all([
            monthQuery,
            pendingQuery,
            todayQuery,
            yesterdayQuery,
        ]);

        const revenueToday = (todayRes.data ?? []).reduce((s: number, o: any) => s + (o.total_amount ?? 0), 0);
        const revenuePrevDay = (yesterdayRes.data ?? []).reduce((s: number, o: any) => s + (o.total_amount ?? 0), 0);

        return {
            totalThisMonth: monthRes.count ?? 0,
            pendingFulfillment: pendingRes.count ?? 0,
            revenueToday,
            revenuePrevDay,
        };
    }

    async updateOrderStatus(id: string, status: OrderStatus, note?: string): Promise<void> {
        const tenantId = this.tenantService.tenantId();
        if (!tenantId) throw new Error('Tenant not selected');

        const { error } = await this.supabase.client
            .from('orders')
            .update({ status, updated_at: new Date().toISOString() })
            .eq('id', id);

        if (error) throw error;

        // Removed manual history insert: The database trigger `trg_log_order_status_change`
        // already logs status changes automatically on UPDATE.
    }

    async updatePaymentStatus(id: string, payment_status: PaymentStatus): Promise<void> {
        const { error } = await this.supabase.client
            .from('orders')
            .update({ payment_status, updated_at: new Date().toISOString() })
            .eq('id', id);

        if (error) throw error;
    }

    async updateInternalNote(id: string, note: string): Promise<void> {
        const { error } = await this.supabase.client
            .from('orders')
            .update({ internal_note: note, updated_at: new Date().toISOString() })
            .eq('id', id);

        if (error) throw error;
    }

    async addTrackingInfo(id: string, info: { tracking_number?: string; tracking_url?: string; shipping_method?: string }): Promise<void> {
        const { error } = await this.supabase.client
            .from('orders')
            .update({
                shipping_method: info.shipping_method ?? null,
                tracking_number: info.tracking_number ?? null,
                tracking_url: info.tracking_url ?? null,
                shipped_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
            })
            .eq('id', id);

        if (error) throw error;
    }

    async assignDeliveryPerson(id: string, delivery_person_id: string | null): Promise<void> {
        const { error } = await this.supabase.client
            .from('orders')
            .update({
                delivery_person_id,
                updated_at: new Date().toISOString(),
            })
            .eq('id', id);

        if (error) throw error;
    }

    async cancelOrder(id: string, reason: string): Promise<void> {
        const { error } = await this.supabase.client
            .from('orders')
            .update({
                status: OrderStatus.Cancelled,
                cancelled_at: new Date().toISOString(),
                cancelled_reason: reason,
                updated_at: new Date().toISOString(),
            })
            .eq('id', id);

        if (error) throw error;
    }

    async processRefund(order: Order, amount: number, reason: string, returnToStock: boolean): Promise<void> {
        const tenantId = this.tenantService.tenantId();
        if (!tenantId) throw new Error('Tenant not selected');

        // 1. Insert refund record
        const { error: refundError } = await this.supabase.client
            .from('refunds')
            .insert({
                tenant_id: tenantId,
                order_id: order.id,
                amount,
                reason,
                status: 'completed', // Assuming successful processing for now
                processed_at: new Date().toISOString()
            });

        if (refundError) throw refundError;

        // 2. Update order payment status
        const totalRefundedSoFar = (order.refunds?.reduce((sum, r) => sum + r.amount, 0) || 0) + amount;
        const newPaymentStatus = totalRefundedSoFar >= order.total_amount
            ? PaymentStatus.Refunded
            : PaymentStatus.PartiallyRefunded;

        const { error: orderError } = await this.supabase.client
            .from('orders')
            .update({
                payment_status: newPaymentStatus,
                status: totalRefundedSoFar >= order.total_amount ? OrderStatus.Refunded : order.status,
                updated_at: new Date().toISOString()
            })
            .eq('id', order.id);

        if (orderError) throw orderError;

        // 3. Return items to stock if requested
        if (returnToStock && order.items && order.items.length > 0) {
            for (const item of order.items) {
                if (item.product_id) {
                    // Get current product stock
                    const { data: product, error: productError } = await this.supabase.client
                        .from('products')
                        .select('stock_quantity, track_inventory')
                        .eq('id', item.product_id)
                        .single();

                    if (!productError && product && product.track_inventory) {
                        await this.supabase.client
                            .from('products')
                            .update({ stock_quantity: (product.stock_quantity || 0) + item.quantity })
                            .eq('id', item.product_id);
                    }
                }

                // If variant_id exists, also return to variant stock if tracked
                if (item.variant_id) {
                    const { data: variant, error: variantError } = await this.supabase.client
                        .from('product_variants')
                        .select('stock_quantity')
                        .eq('id', item.variant_id)
                        .single();

                    if (!variantError && variant) {
                        await this.supabase.client
                            .from('product_variants')
                            .update({ stock_quantity: (variant.stock_quantity || 0) + item.quantity })
                            .eq('id', item.variant_id);
                    }
                }
            }
        }

        // 4. Add status history entry
        await this.supabase.client.from('order_status_history').insert({
            order_id: order.id,
            tenant_id: tenantId,
            new_status: totalRefundedSoFar >= order.total_amount ? OrderStatus.Refunded : order.status,
            note: `Refund of $${amount} processed for reason: ${reason}`
        });
    }
}
