import { ThemePreset, ThemeTokens, ThemePresetId, FontOption, TypographyPairing } from '@core/models';

export const AVAILABLE_FONTS: FontOption[] = [
    { name: 'Inter', family: '"Inter", sans-serif', category: 'sans-serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap' },
    { name: 'Playfair Display', family: '"Playfair Display", serif', category: 'serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;0,900;1,400&display=swap' },
    { name: 'Outfit', family: '"Outfit", sans-serif', category: 'sans-serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800;900&display=swap' },
    { name: 'Poppins', family: '"Poppins", sans-serif', category: 'sans-serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap' },
    { name: 'Space Grotesk', family: '"Space Grotesk", sans-serif', category: 'display', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap' },
    { name: 'Cormorant Garamond', family: '"Cormorant Garamond", serif', category: 'serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;500;600;700&display=swap' },
    { name: 'Montserrat', family: '"Montserrat", sans-serif', category: 'sans-serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700;800;900&display=swap' },
    { name: 'Merriweather', family: '"Merriweather", serif', category: 'serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap' },
    { name: 'Plus Jakarta Sans', family: '"Plus Jakarta Sans", sans-serif', category: 'sans-serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap' },
    { name: 'Roboto', family: '"Roboto", sans-serif', category: 'sans-serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap' },
    { name: 'Cinzel', family: '"Cinzel", serif', category: 'serif', googleFontUrl: 'https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700;900&display=swap' },
];

export const TYPOGRAPHY_PAIRINGS: TypographyPairing[] = [
    {
        id: 'elegant',
        name: 'Elegante',
        tagline: 'Lujo, romance y sofisticación',
        description: 'Combinación distinguida entre Playfair Display para encabezados y Outfit para cuerpo y botones.',
        font_heading: '"Playfair Display", serif',
        font_body: '"Outfit", sans-serif',
        font_button: '"Outfit", sans-serif',
        font_weight_heading: '700',
    },
    {
        id: 'modern',
        name: 'Moderna',
        tagline: 'Limpia, directa y contemporánea',
        description: 'Combinación versátil con Plus Jakarta Sans en títulos y botones junto con la legibilidad de Inter.',
        font_heading: '"Plus Jakarta Sans", sans-serif',
        font_body: '"Inter", sans-serif',
        font_button: '"Plus Jakarta Sans", sans-serif',
        font_weight_heading: '800',
    },
    {
        id: 'editorial',
        name: 'Editorial',
        tagline: 'Estilo prensa, calidez y lectura atemporal',
        description: 'Inspirada en periódicos y revistas con Merriweather en títulos y cuerpo, equilibrada con botones en Inter.',
        font_heading: '"Merriweather", serif',
        font_body: '"Merriweather", serif',
        font_button: '"Inter", sans-serif',
        font_weight_heading: '900',
    },
    {
        id: 'geometric',
        name: 'Geométrica',
        tagline: 'Vanguardista, audaz y estructurada',
        description: 'Trazos geométricos modernos usando Space Grotesk en títulos y botones con Poppins en texto principal.',
        font_heading: '"Space Grotesk", sans-serif',
        font_body: '"Poppins", sans-serif',
        font_button: '"Space Grotesk", sans-serif',
        font_weight_heading: '700',
    },
    {
        id: 'classic',
        name: 'Clásica',
        tagline: 'Herencia, sobriedad y distinción tradicional',
        description: 'Cormorant Garamond en títulos combinada con la neutralidad funcional de Roboto para cuerpo y acciones.',
        font_heading: '"Cormorant Garamond", serif',
        font_body: '"Roboto", sans-serif',
        font_button: '"Roboto", sans-serif',
        font_weight_heading: '600',
    },
];

export const THEME_PRESETS: Record<ThemePresetId, ThemePreset> = {
    minimalist: {
        id: 'minimalist',
        name: 'Minimalista',
        tagline: 'Sobrio, puro y libre de distracciones',
        description: 'Enfocado en la fotografía de producto con tipografía limpia, bordes rectos fidedignos y contraste monocromático.',
        category: 'Moda, Diseño, Arquitectura',
        preview_bg: '#ffffff',
        preview_accent: '#000000',
        tokens: {
            theme_id: 'minimalist',
            theme_name: 'Minimalista',
            font_heading: '"Inter", sans-serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'none',
            border_radius_card: 'none',
            border_radius_button: 'none',
            border_radius_badge: 'none',
            border_width: '1px',
            shadow_style: 'none',
            spacing_density: 'normal',
            max_content_width: '1280px',
            button_shape: 'sharp',
            button_style: 'filled',
            button_transform: 'uppercase',
            card_style: 'minimal',
            card_image_aspect: '4/5',
            header_style: 'minimal',
            hero_style: 'left',
            colors: {
                primary: '#000000',
                secondary: '#171717',
                accent: '#404040',
                background: '#ffffff',
                surface: '#fafafa',
                header: '#ffffff',
                footer: '#ffffff',
                text_primary: '#0a0a0a',
                text_muted: '#737373',
                border: '#e5e5e5',
            },
        },
    },

    editorial: {
        id: 'editorial',
        name: 'Editorial',
        tagline: 'Estilo magazine, historias y elegancia literaria',
        description: 'Inspirado en publicaciones impresas y revistas de lujo. Combina tipografía serif refinada con tonos crema cálidos.',
        category: 'Libros, Arte, Papelería, Estilo de vida',
        preview_bg: '#fcfbf7',
        preview_accent: '#c25e3d',
        tokens: {
            theme_id: 'editorial',
            theme_name: 'Editorial',
            font_heading: '"Playfair Display", serif',
            font_body: '"Merriweather", serif',
            font_size_scale: 'spacious',
            border_radius: 'sm',
            border_radius_card: 'sm',
            border_radius_button: 'sm',
            border_radius_badge: 'sm',
            border_width: '1px',
            shadow_style: 'subtle',
            spacing_density: 'spacious',
            max_content_width: '1280px',
            button_shape: 'rounded',
            button_style: 'outline',
            button_transform: 'none',
            card_style: 'magazine',
            card_image_aspect: '3/4',
            header_style: 'centered',
            hero_style: 'centered',
            colors: {
                primary: '#1c1917',
                secondary: '#44403c',
                accent: '#c25e3d',
                background: '#fcfbf7',
                surface: '#f5f3ec',
                header: '#f7f4eb',
                footer: '#eeebe2',
                text_primary: '#1c1917',
                text_muted: '#78716c',
                border: '#e7e5e4',
            },
        },
    },

    fashion: {
        id: 'fashion',
        name: 'Fashion & Alta Costura',
        tagline: 'Glamour, contraste dramático y siluetas delgadas',
        description: 'Vanguardista y sofisticado. Resalta colecciones de moda con proporciones alargadas y dorados de alta costura.',
        category: 'Moda, Joyería, Cosmética Premium',
        preview_bg: '#fafafa',
        preview_accent: '#d4af37',
        tokens: {
            theme_id: 'fashion',
            theme_name: 'Fashion & Alta Costura',
            font_heading: '"Cormorant Garamond", serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'none',
            border_radius_card: 'none',
            border_radius_button: 'none',
            border_radius_badge: 'full',
            border_width: '1px',
            shadow_style: 'none',
            spacing_density: 'spacious',
            max_content_width: '1440px',
            button_shape: 'sharp',
            button_style: 'outline',
            button_transform: 'uppercase',
            card_style: 'minimal',
            card_image_aspect: '3/4',
            header_style: 'floating',
            hero_style: 'full',
            colors: {
                primary: '#111111',
                secondary: '#262626',
                accent: '#d4af37',
                background: '#fafafa',
                surface: '#ffffff',
                header: 'rgba(250, 250, 250, 0.95)',
                footer: '#111111',
                text_primary: '#111111',
                text_muted: '#737373',
                border: '#e5e5e5',
            },
        },
    },

    tech: {
        id: 'tech',
        name: 'Tecnología & Gadgets',
        tagline: 'Futurista, neón e interfaces cristalinas',
        description: 'Para tiendas de electrónica y productos digitales. Incorpora esquinas suavizadas, sombras de resplandor e insignias modernas.',
        category: 'Tecnología, Gaming, Software, Audio',
        preview_bg: '#0f172a',
        preview_accent: '#06b6d4',
        tokens: {
            theme_id: 'tech',
            theme_name: 'Tecnología & Gadgets',
            font_heading: '"Space Grotesk", sans-serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'xl',
            border_radius_card: '2xl',
            border_radius_button: 'xl',
            border_radius_badge: 'md',
            border_width: '1px',
            shadow_style: 'glow',
            spacing_density: 'compact',
            max_content_width: '1440px',
            button_shape: 'rounded',
            button_style: 'filled',
            button_transform: 'none',
            card_style: 'glass',
            card_image_aspect: '1/1',
            header_style: 'floating',
            hero_style: 'split',
            colors: {
                primary: '#6366f1',
                secondary: '#0f172a',
                accent: '#06b6d4',
                background: '#0f172a',
                surface: '#1e293b',
                header: 'rgba(15, 23, 42, 0.85)',
                footer: '#090d16',
                text_primary: '#f8fafc',
                text_muted: '#94a3b8',
                border: '#334155',
            },
        },
    },

    restaurant: {
        id: 'restaurant',
        name: 'Restaurante & Gourmet',
        tagline: 'Cálido, apetitoso y texturas envolventes',
        description: 'Pensado para gastronomía, cafés y repostería. Colores cálidos (almendra, café espresso y terracota) con esquinas acogedoras.',
        category: 'Restaurantes, Cafeterías, Pastelería, Bebidas',
        preview_bg: '#faf7f2',
        preview_accent: '#e05d26',
        tokens: {
            theme_id: 'restaurant',
            theme_name: 'Restaurante & Gourmet',
            font_heading: '"Outfit", sans-serif',
            font_body: '"Plus Jakarta Sans", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'xl',
            border_radius_card: '2xl',
            border_radius_button: 'full',
            border_radius_badge: 'full',
            border_width: '1px',
            shadow_style: 'elevated',
            spacing_density: 'normal',
            max_content_width: '1280px',
            button_shape: 'pill',
            button_style: 'filled',
            button_transform: 'none',
            card_style: 'elevated',
            card_image_aspect: '1/1',
            header_style: 'classic',
            hero_style: 'centered',
            colors: {
                primary: '#e05d26',
                secondary: '#291c18',
                accent: '#556b2f',
                background: '#faf7f2',
                surface: '#ffffff',
                header: '#ffffff',
                footer: '#291c18',
                text_primary: '#291c18',
                text_muted: '#786d69',
                border: '#ebdcd3',
            },
        },
    },

    artisan: {
        id: 'artisan',
        name: 'Artesanal & Botánico',
        tagline: 'Orgánico, consciente y origen natural',
        description: 'Tonalidades tierra, verde musgo y papel craft. Transmite un sentimiento hecho a mano, sostenible y ecológico.',
        category: 'Artesanías, Botánica, Velas, Cerámica',
        preview_bg: '#f7f3ec',
        preview_accent: '#9c4a2f',
        tokens: {
            theme_id: 'artisan',
            theme_name: 'Artesanal & Botánico',
            font_heading: '"Merriweather", serif',
            font_body: '"Outfit", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'md',
            border_radius_card: 'lg',
            border_radius_button: 'md',
            border_radius_badge: 'md',
            border_width: '1px',
            shadow_style: 'subtle',
            spacing_density: 'normal',
            max_content_width: '1024px',
            button_shape: 'rounded',
            button_style: 'filled',
            button_transform: 'none',
            card_style: 'bordered',
            card_image_aspect: '4/5',
            header_style: 'centered',
            hero_style: 'minimal',
            colors: {
                primary: '#9c4a2f',
                secondary: '#60725a',
                accent: '#d97706',
                background: '#f7f3ec',
                surface: '#efe9df',
                header: '#f2ece2',
                footer: '#2c2825',
                text_primary: '#2c2825',
                text_muted: '#6e6761',
                border: '#dfd7ca',
            },
        },
    },

    luxury: {
        id: 'luxury',
        name: 'Lujo & Exclusividad',
        tagline: 'Opulencia, oro pulido y presencia majestuosa',
        description: 'Fondo de obsidiana profunda con acentos en oro brillante, tipografía romana augusta y botones refinados.',
        category: 'Relojería, Alta Joyería, Supercoches, Propiedades',
        preview_bg: '#0a0a0a',
        preview_accent: '#c5a059',
        tokens: {
            theme_id: 'luxury',
            theme_name: 'Lujo & Exclusividad',
            font_heading: '"Cinzel", serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'compact',
            border_radius: 'sm',
            border_radius_card: 'sm',
            border_radius_button: 'sm',
            border_radius_badge: 'none',
            border_width: '1px',
            shadow_style: 'elevated',
            spacing_density: 'spacious',
            max_content_width: '1280px',
            button_shape: 'sharp',
            button_style: 'outline',
            button_transform: 'uppercase',
            card_style: 'bordered',
            card_image_aspect: '3/4',
            header_style: 'bold',
            hero_style: 'full',
            colors: {
                primary: '#c5a059',
                secondary: '#1c1917',
                accent: '#e2c380',
                background: '#0a0a0a',
                surface: '#141414',
                header: '#0d0d0d',
                footer: '#050505',
                text_primary: '#f9f8f6',
                text_muted: '#a1a1aa',
                border: '#2a2419',
            },
        },
    },

    sport: {
        id: 'sport',
        name: 'Deportivo & Fuerza',
        tagline: 'Alto rendimiento, neón vibrante y velocidad',
        description: 'Diseño lleno de energía, tipografía condensada en negrita, colores eléctricos y tarjetas de alto impacto visual.',
        category: 'Deportes, Suplementos, Fitness, Moda urbana',
        preview_bg: '#111315',
        preview_accent: '#ff4713',
        tokens: {
            theme_id: 'sport',
            theme_name: 'Deportivo & Fuerza',
            font_heading: '"Montserrat", sans-serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'md',
            border_radius_card: 'lg',
            border_radius_button: 'md',
            border_radius_badge: 'full',
            border_width: '2px',
            shadow_style: 'hard',
            spacing_density: 'compact',
            max_content_width: '1440px',
            button_shape: 'rounded',
            button_style: 'filled',
            button_transform: 'uppercase',
            card_style: 'bordered',
            card_image_aspect: '1/1',
            header_style: 'bold',
            hero_style: 'split',
            colors: {
                primary: '#ff4713',
                secondary: '#111315',
                accent: '#2563eb',
                background: '#111315',
                surface: '#1c1f24',
                header: '#111315',
                footer: '#0a0b0d',
                text_primary: '#ffffff',
                text_muted: '#9ca3af',
                border: '#2e333d',
            },
        },
    },

    dark: {
        id: 'dark',
        name: 'Modo Oscuro Puro',
        tagline: 'Elegancia nocturna, descanso visual y luces neón',
        description: 'Tono oscuro zinc profundo con acentos violeta resplandecientes. Ideal para experiencias inmersivas nocturnas.',
        category: 'Moda nocturna, Cripto, Electrónica, Arte digital',
        preview_bg: '#09090b',
        preview_accent: '#a855f7',
        tokens: {
            theme_id: 'dark',
            theme_name: 'Modo Oscuro Puro',
            font_heading: '"Plus Jakarta Sans", sans-serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'xl',
            border_radius_card: 'xl',
            border_radius_button: 'xl',
            border_radius_badge: 'full',
            border_width: '1px',
            shadow_style: 'glow',
            spacing_density: 'normal',
            max_content_width: '1440px',
            button_shape: 'rounded',
            button_style: 'filled',
            button_transform: 'none',
            card_style: 'elevated',
            card_image_aspect: '4/5',
            header_style: 'floating',
            hero_style: 'centered',
            colors: {
                primary: '#a855f7',
                secondary: '#18181b',
                accent: '#38bdf8',
                background: '#09090b',
                surface: '#18181b',
                header: 'rgba(24, 24, 27, 0.9)',
                footer: '#040405',
                text_primary: '#f4f4f5',
                text_muted: '#a1a1aa',
                border: '#27272a',
            },
        },
    },

    colorful: {
        id: 'colorful',
        name: 'Colorido & Divertido',
        tagline: 'Alegre, burbujeante y lleno de vida',
        description: 'Formas súper redondeadas tipo píldora, degradados vibrantes y paleta alegre llena de energía y positividad.',
        category: 'Juguetes, Niños, Regalos, Golosinas, Fiestas',
        preview_bg: '#fdf8ff',
        preview_accent: '#ec4899',
        tokens: {
            theme_id: 'colorful',
            theme_name: 'Colorido & Divertido',
            font_heading: '"Poppins", sans-serif',
            font_body: '"Outfit", sans-serif',
            font_size_scale: 'normal',
            border_radius: '2xl',
            border_radius_card: '2xl',
            border_radius_button: 'full',
            border_radius_badge: 'full',
            border_width: '2px',
            shadow_style: 'colored',
            spacing_density: 'normal',
            max_content_width: '1280px',
            button_shape: 'pill',
            button_style: 'filled',
            button_transform: 'none',
            card_style: 'playful',
            card_image_aspect: '1/1',
            header_style: 'classic',
            hero_style: 'centered',
            colors: {
                primary: '#6366f1',
                secondary: '#ec4899',
                accent: '#f59e0b',
                background: '#fdf8ff',
                surface: '#ffffff',
                header: '#ffffff',
                footer: '#f3e8ff',
                text_primary: '#1e1b4b',
                text_muted: '#6b7280',
                border: '#e0e7ff',
            },
        },
    },

    custom: {
        id: 'custom',
        name: 'Personalizado',
        tagline: 'Configuración totalmente a medida',
        description: 'Tema personalizado ajustado de forma granular por el administrador de la tienda.',
        category: 'A medida',
        preview_bg: '#ffffff',
        preview_accent: '#3b82f6',
        tokens: {
            theme_id: 'custom',
            theme_name: 'Personalizado',
            font_heading: '"Inter", sans-serif',
            font_body: '"Inter", sans-serif',
            font_size_scale: 'normal',
            border_radius: 'lg',
            border_radius_card: 'lg',
            border_radius_button: 'lg',
            border_radius_badge: 'md',
            border_width: '1px',
            shadow_style: 'subtle',
            spacing_density: 'normal',
            max_content_width: '1280px',
            button_shape: 'rounded',
            button_style: 'filled',
            button_transform: 'none',
            card_style: 'bordered',
            card_image_aspect: '4/5',
            header_style: 'minimal',
            hero_style: 'centered',
            colors: {
                primary: '#000000',
                secondary: '#1e293b',
                accent: '#3b82f6',
                background: '#ffffff',
                surface: '#f8fafc',
                header: '#ffffff',
                footer: '#ffffff',
                text_primary: '#0f172a',
                text_muted: '#64748b',
                border: '#e2e8f0',
            },
        },
    },
};

/**
 * Maps ThemeTokens to CSS custom variables dictionary
 */
export function themeTokensToCssVars(tokens: ThemeTokens): Record<string, string> {
    const radiusMap: Record<string, string> = {
        none: '0px',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
    };

    const shadowMap: Record<string, string> = {
        none: 'none',
        subtle: '0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
        elevated: '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.05)',
        hard: '4px 4px 0px 0px rgba(0, 0, 0, 0.9)',
        glow: '0 0 20px -3px rgba(99, 102, 241, 0.35)',
        colored: '0 10px 20px -5px rgba(99, 102, 241, 0.25)',
    };

    const gridGapMap: Record<string, string> = {
        compact: '1rem',
        normal: '1.5rem',
        spacious: '2.5rem',
    };

    const sectionPyMap: Record<string, string> = {
        compact: '2.5rem',
        normal: '4rem',
        spacious: '6rem',
    };

    return {
        '--store-font-heading': tokens.font_heading || '"Inter", sans-serif',
        '--store-font-body': tokens.font_body || '"Inter", sans-serif',
        '--store-font-button': tokens.font_button || tokens.font_body || '"Inter", sans-serif',
        '--store-font-weight-heading': tokens.font_weight_heading || '700',
        '--store-font-size-base': tokens.font_size_base || '16px',
        '--store-line-height': tokens.line_height || '1.5',
        '--store-letter-spacing': tokens.letter_spacing || '0em',
        '--store-radius': radiusMap[tokens.border_radius || 'lg'],
        '--store-radius-card': radiusMap[tokens.border_radius_card || tokens.border_radius || 'lg'],
        '--store-radius-btn': radiusMap[tokens.border_radius_button || tokens.border_radius || 'lg'],
        '--store-radius-badge': radiusMap[tokens.border_radius_badge || 'full'],
        '--store-border-width': tokens.border_width || '1px',
        '--store-shadow': shadowMap[tokens.shadow_style || 'subtle'],
        '--store-btn-transform': tokens.button_transform || 'none',

        // Layout Tokens
        '--store-max-width': tokens.max_content_width || '1280px',
        '--store-grid-gap': gridGapMap[tokens.spacing_density || 'normal'],
        '--store-section-py': sectionPyMap[tokens.spacing_density || 'normal'],

        // Legacy compatibility variables
        '--primary-color': tokens.colors.primary,
        '--secondary-color': tokens.colors.secondary,
        '--accent-color': tokens.colors.accent,
        '--background-color': tokens.colors.background,
        '--header-color': tokens.colors.header,
        '--footer-color': tokens.colors.footer,

        // Extended theme color variables
        '--store-color-primary': tokens.colors.primary,
        '--store-color-primary-contrast': getContrastColor(tokens.colors.primary),
        '--store-color-secondary': tokens.colors.secondary,
        '--store-color-secondary-contrast': getContrastColor(tokens.colors.secondary),
        '--store-color-accent': tokens.colors.accent,
        '--store-color-accent-contrast': getContrastColor(tokens.colors.accent),
        '--store-color-bg': tokens.colors.background,
        '--store-color-surface': tokens.colors.surface || '#ffffff',
        '--store-color-header': tokens.colors.header,
        '--store-color-footer': tokens.colors.footer,
        '--store-color-text': tokens.colors.text_primary || '#0a0a0a',
        '--store-color-muted': tokens.colors.text_muted || '#737373',
        '--store-color-border': tokens.colors.border || '#e5e5e5',
        '--store-color-btn-text': getContrastColor(tokens.colors.primary),
    };
}

/**
 * Computes high-contrast text color (white or dark) based on background hex color luminance
 */
export function getContrastColor(hexColor: string | null | undefined, defaultDark = '#0f172a', defaultLight = '#ffffff'): string {
    if (!hexColor) return defaultLight;
    let hex = hexColor.replace('#', '').trim();
    if (hex.length === 3) {
        hex = hex.split('').map(c => c + c).join('');
    }
    if (hex.length !== 6) return defaultLight;
    const r = parseInt(hex.substring(0, 2), 16);
    const g = parseInt(hex.substring(2, 4), 16);
    const b = parseInt(hex.substring(4, 6), 16);
    if (isNaN(r) || isNaN(g) || isNaN(b)) return defaultLight;
    // YIQ formula for perceived luminance
    const yiq = (r * 299 + g * 587 + b * 114) / 1000;
    return yiq >= 150 ? defaultDark : defaultLight;
}
